main:
  device: cuda
  dataset: scannet # scannet
  scene_name: scene0011_00
  feature_map_path: hovsg/data/sem_seg/Replica/office0
  replica_dataset_gt_path: hovsg/data/Replica_original
  scannet_dataset_gt_path: ""
  # only for replica
  replica_color_map: hovsg/labels/class_id_colors.json
models:
  clip:
    general_type: ViT-L-14
    type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: checkpoints/laion2b_s32b_b79k.bin # checkpoints/ovseg_clipl14_9a1909.pth checkpoints/laion2b_s32b_b79k.bin
